- name: playbook for git
  hosts: vagrant
  sudo: True
  tasks:
 
 
  - name: create a user
    postgresql_user:
       name: kbrom
       password: kbrom
    sudo: True
    sudo_user: postgres
    
    
   
