- name: playbook for git
  hosts: vagrant
  sudo: True
  
  vars:
    user: "{{ ansible_ssh_user }}"
    proj_name: mezzanine-example
    venv_home: "{{ ansible_env.HOME }}"
    venv_path: "{{ venv_home }}/{{ proj_name }}"
    proj_dirname: project
    proj_path: "{{ venv_path }}/{{ proj_dirname }}"
    reqs_path: requirements.txt
    manage: "{{ python }} {{ proj_path }}/manage.py"
    live_hostname: 192.168.33.10.xip.io
    domains:
      - 192.168.33.10.xip.io
      - www.192.168.33.10.xip.io
    repo_url: git@github.com:lorin/mezzanine-example.git
    gunicorn_port: 8000
    locale: en_US.UTF-8
    # Variables below don't appear in Mezzanine's fabfile.py
    # but I've added them for convenience
    conf_path: /etc/nginx/conf
    tls_enabled: True
    python: "{{ venv_path }}/bin/python"
    database_name: "{{ proj_name }}"
    database_user: "{{ proj_name }}"
    database_host: localhost
    database_port: 5432
    gunicorn_proc_name: mezzanine
    vars_files:
      - secrets.yml
  Tasks:
   - name: create a user
     postgresql_user:
         name: kbrom
         password: kbrom
     sudo: True
     sudo_user: postgres
    
   - name: create the database
     postgresql_db:
       name: ansible
       owner: kbrom
       encoding: UTF8
       lc_ctype: en_US.UTF-8
       lc_collate: en_US.UTF-8
       template: template0
     sudo: True
     sudo_user: postgres
  
   
