- name: playbook for git
  hosts: vagrant
  sudo: True
  tasks:
 
 
  - name: create a user
    postgresql_user:
       name: kbrom
       password: kbrom
    sudo: True
    sudo_user: postgres
    
  - name: create the database
    postgresql_db:
     name: ansible
     owner: kbrom
     encoding: UTF8
     lc_ctype: en_US.UTF-8
     lc_collate: en_US.UTF-8
     template: template0
  sudo: True
  sudo_user: postgres
  
   
